#############################################################################
# Makefile for building: widgets_
# Generated by qmake (2.01a) (Qt 4.6.2) on: Fri Apr 20 16:15:10 2012
# Project:  widgets_.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile widgets_.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = thrustbar.cpp \
		map.cpp \
		main.cpp \
		headingindicator.cpp \
		avionicstelemetry.cpp \
		altimeter.cpp moc_thrustbar.cpp \
		moc_map.cpp \
		moc_headingindicator.cpp \
		moc_avionicstelemetry.cpp \
		moc_altimeter.cpp
OBJECTS       = thrustbar.o \
		map.o \
		main.o \
		headingindicator.o \
		avionicstelemetry.o \
		altimeter.o \
		moc_thrustbar.o \
		moc_map.o \
		moc_headingindicator.o \
		moc_avionicstelemetry.o \
		moc_altimeter.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		widgets_.pro
QMAKE_TARGET  = widgets_
DESTDIR       = 
TARGET        = widgets_

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_thrustbar.h ui_avionicstelemetry.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: widgets_.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile widgets_.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile widgets_.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/widgets_1.0.0 || $(MKDIR) .tmp/widgets_1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/widgets_1.0.0/ && $(COPY_FILE) --parents thrustbar.h map.h headingindicator.h avionicstelemetry.h altimeter.h .tmp/widgets_1.0.0/ && $(COPY_FILE) --parents thrustbar.cpp map.cpp main.cpp headingindicator.cpp avionicstelemetry.cpp altimeter.cpp .tmp/widgets_1.0.0/ && $(COPY_FILE) --parents thrustbar.ui avionicstelemetry.ui .tmp/widgets_1.0.0/ && (cd `dirname .tmp/widgets_1.0.0` && $(TAR) widgets_1.0.0.tar widgets_1.0.0 && $(COMPRESS) widgets_1.0.0.tar) && $(MOVE) `dirname .tmp/widgets_1.0.0`/widgets_1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/widgets_1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_thrustbar.cpp moc_map.cpp moc_headingindicator.cpp moc_avionicstelemetry.cpp moc_altimeter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_thrustbar.cpp moc_map.cpp moc_headingindicator.cpp moc_avionicstelemetry.cpp moc_altimeter.cpp
moc_thrustbar.cpp: thrustbar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) thrustbar.h -o moc_thrustbar.cpp

moc_map.cpp: map.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) map.h -o moc_map.cpp

moc_headingindicator.cpp: headingindicator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headingindicator.h -o moc_headingindicator.cpp

moc_avionicstelemetry.cpp: avionicstelemetry.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) avionicstelemetry.h -o moc_avionicstelemetry.cpp

moc_altimeter.cpp: altimeter.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) altimeter.h -o moc_altimeter.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_thrustbar.h ui_avionicstelemetry.h
compiler_uic_clean:
	-$(DEL_FILE) ui_thrustbar.h ui_avionicstelemetry.h
ui_thrustbar.h: thrustbar.ui
	/usr/bin/uic-qt4 thrustbar.ui -o ui_thrustbar.h

ui_avionicstelemetry.h: avionicstelemetry.ui
	/usr/bin/uic-qt4 avionicstelemetry.ui -o ui_avionicstelemetry.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

thrustbar.o: thrustbar.cpp thrustbar.h \
		ui_thrustbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thrustbar.o thrustbar.cpp

map.o: map.cpp map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map.o map.cpp

main.o: main.cpp avionicstelemetry.h \
		altimeter.h \
		thrustbar.h \
		headingindicator.h \
		map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

headingindicator.o: headingindicator.cpp headingindicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headingindicator.o headingindicator.cpp

avionicstelemetry.o: avionicstelemetry.cpp avionicstelemetry.h \
		ui_avionicstelemetry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o avionicstelemetry.o avionicstelemetry.cpp

altimeter.o: altimeter.cpp altimeter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o altimeter.o altimeter.cpp

moc_thrustbar.o: moc_thrustbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thrustbar.o moc_thrustbar.cpp

moc_map.o: moc_map.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_map.o moc_map.cpp

moc_headingindicator.o: moc_headingindicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headingindicator.o moc_headingindicator.cpp

moc_avionicstelemetry.o: moc_avionicstelemetry.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_avionicstelemetry.o moc_avionicstelemetry.cpp

moc_altimeter.o: moc_altimeter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_altimeter.o moc_altimeter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

